#!/bin/bash

echo "═══════════════════════════════════════════════════════════════════════════"
echo "DEPLOYMENT INSTRUCTIONS: Overwrite Protection to Staging"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Code committed and pushed to GitHub"
echo "   Branch: feat/ops-dashboard-exports"
echo "   Commit: 26f24c9 - feat(upload): Add settlement protection to overwrite feature"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "MANUAL DEPLOYMENT STEPS (SSH keys not accessible)"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "BACKEND DEPLOYMENT:"
echo "-------------------"
echo "1. SSH to EC2 (use AWS Console or your SSH method):"
echo "   ssh -i <your-key> ec2-user@13.201.179.44"
echo ""
echo "2. Navigate to project directory:"
echo "   cd /home/ec2-user/ops-dashboard"
echo ""
echo "3. Pull latest code:"
echo "   git pull origin feat/ops-dashboard-exports"
echo ""
echo "4. Verify the commit:"
echo "   git log -1 --oneline"
echo "   # Should show: 26f24c9 feat(upload): Add settlement protection to overwrite feature"
echo ""
echo "5. Restart upload API:"
echo "   pm2 restart upload-api"
echo ""
echo "6. Check logs for errors:"
echo "   pm2 logs upload-api --lines 50"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "FRONTEND DEPLOYMENT:"
echo "-------------------"
echo "7. Build frontend (run locally on your machine):"
echo "   npm run build"
echo ""
echo "8. Deploy to S3:"
echo "   aws s3 sync dist-ops/ s3://shantanu-settlepaisa-ops-staging/ --delete"
echo ""
echo "9. Clear browser cache and test"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "VERIFICATION:"
echo "-------------------"
echo "10. Test overwrite with PENDING transactions (should work)"
echo "11. Test overwrite with SETTLED transactions (should block with error)"
echo "12. Verify error message is clear and actionable"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
